# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r azure_pipelines_requirements.txt
    python -m pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    python setup.py bdist_wheel
  displayName: 'Build'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'PBQ/pbq_python_feed'
    pythonUploadServiceConnection: 'PythonPackageUpload'
  displayName: 'Authenticate to Azure Artifacts server'

- script: |
    echo $(PYPIRC_PATH)
    cat $(PYPIRC_PATH)
    python3 -m twine upload -r pbq_python_feed --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Publish to Azure Artifacts'
